// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://keclsvbqocznaehbuapk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlY2xzdmJxb2N6bmFlaGJ1YXBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzU5OTIsImV4cCI6MjA2MzY1MTk5Mn0.zw5D9968rfc6qIIRsXwESr_gI26RVRVmUIaSlmMpUnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);